port: 7890
socks-port: 7891
mixed-port: 7893
allow-interface-control: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  fallback:
  - 8.8.8.8
  - 1.1.1.1
proxies:
- name: '[æœªçŸ¥] JUICITY_157.254.223.48 [0ms] (18:18)'
  type: juicity
  server: 157.254.223.48
  port: 45889
  uuid: abbf6900-2bfb-4019-89e4-4875e831cea8
  sni: us3.193919.xyz
  client-fingerprint: chrome
  tls-fragment: 10-30,5-10
  tfo: true
  _geo: æœªçŸ¥
- name: '[ç¾å›½] VLESS_157.254.223.44 [24ms] (18:18)'
  type: vless
  server: 157.254.223.44
  port: 18959
  uuid: d0b3e27d-bbfc-4a3b-8e60-6973de8fcefa
  password: null
  cipher: null
  sni: itunes.apple.com
  client-fingerprint: chrome
  tls-fragment: 10-30,5-10
  tfo: true
  _geo: ç¾å›½
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - âš¡ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
  - ğŸŒ å‰©ä½™åœ°åŒº
  - DIRECT
  - '[æœªçŸ¥] JUICITY_157.254.223.48 [0ms] (18:18)'
  - '[ç¾å›½] VLESS_157.254.223.44 [24ms] (18:18)'
- name: ğŸ“º å›½é™…æµåª’ä½“
  type: select
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
  - DIRECT
- name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  type: select
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
  - DIRECT
- name: â“‚ï¸ å¾®è½¯æœåŠ¡
  type: select
  proxies:
  - DIRECT
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
- name: ğŸ è‹¹æœæœåŠ¡
  type: select
  proxies:
  - DIRECT
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
- name: âš¡ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
  - '[æœªçŸ¥] JUICITY_157.254.223.48 [0ms] (18:18)'
  - '[ç¾å›½] VLESS_157.254.223.44 [24ms] (18:18)'
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  type: select
  proxies: []
- name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  type: select
  proxies:
  - '[ç¾å›½] VLESS_157.254.223.44 [24ms] (18:18)'
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  type: select
  proxies: []
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹
  type: select
  proxies: []
- name: ğŸŒ å‰©ä½™åœ°åŒº
  type: select
  proxies:
  - '[æœªçŸ¥] JUICITY_157.254.223.48 [0ms] (18:18)'
rules:
- DOMAIN-KEYWORD,adserver,REJECT
- DOMAIN-SUFFIX,googleadservices.com,REJECT
- DOMAIN-SUFFIX,netflix.com,ğŸ“º å›½é™…æµåª’ä½“
- DOMAIN-SUFFIX,netflix.net,ğŸ“º å›½é™…æµåª’ä½“
- DOMAIN-SUFFIX,youtube.com,ğŸ“º å›½é™…æµåª’ä½“
- DOMAIN-SUFFIX,googlevideo.com,ğŸ“º å›½é™…æµåª’ä½“
- DOMAIN-SUFFIX,telegram.org,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
- IP-CIDR,91.108.4.0/22,ğŸ“² ç”µæŠ¥æ¶ˆæ¯,no-resolve
- DOMAIN-SUFFIX,microsoft.com,â“‚ï¸ å¾®è½¯æœåŠ¡
- DOMAIN-SUFFIX,apple.com,ğŸ è‹¹æœæœåŠ¡
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
