name: 自动更新节点订阅

on:
  workflow_dispatch:      # 允许手动点击运行
  schedule:
    - cron: '0 */6 * * *'  # 每6小时自动运行一次
  push:
    paths:
      - 'urls/manual_json.txt' # 当你手动修改源文件时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # 必须开启写入权限，否则无法推送到仓库

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/checkout@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install pyyaml

      - name: 运行解析脚本
        run: python main.py

      - name: 检查生成的文件
        run: |
          ls -R ./sub

      - name: 提交并推送更改
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add sub/*
          # 只有在文件有变动时才提交，防止报错
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update nodes: $(date +'%Y-%m-%d %H:%M')" && git push)
